### PR TITLE
Create .readthedocs.yml

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz How can I access RTD? If I understand the docs correctly, there should be an SSO option, and then we should be able to access everything via Github integration?
https://docs.readthedocs.io/en/stable/guides/setup-single-sign-on-github-gitlab-bitbucket.html#grant-access-to-administer-a-project

I don't seem to be able to access anything after logging in via Github. There are several repositories that have been failing builds for some time, because the build status isn't reported in the PRs.

**Comment by webknjaz** [comment]
@Dreamsorcerer SSO only logs you into the platform. There's no GH-based RBAC. You need to be added to each project manually.

**Comment by webknjaz** [comment]
@Dreamsorcerer per https://readthedocs.org/projects/aiohttp-jinja2/, only @asvetlov has access to that RTD project. If he doesn't show up, we can create a new one, with a new project slug, and use that. I can point a CNAME at that, if needed.

**Comment by Dreamsorcerer** [comment]
Created #781. Not urgent, so can sit on it till next year or so and see if he's around.

**Pull request merged**
