### PR TITLE
Fix installation error due to missing CHANGES.rst.

### PR DESCRIPTION
**Pull request by jameshilliard**
Fixes:
```python
Traceback (most recent call last):
  File "/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/setup.py", line 41, in <module>
    long_description="\n\n".join((read("README.rst"), read("CHANGES.rst"))),
  File "/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/setup.py", line 29, in read
    return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/CHANGES.rst'
```

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
Thanks!

**Comment by jameshilliard** [comment]
@asvetlov 

> Merge branch 'master' into fix-install

I think you did the merge in the wrong direction.

**Comment by webknjaz** [comment]
@jameshilliard it's not wrong. It's meant to confirm that this branch is up to date with the current master.

**Comment by jameshilliard** [comment]
@webknjaz Wouldn't that be obvious from the commit log? Or am I missing something?

**Comment by asvetlov** [comment]
That's how github works when I enable "Require branches to be up to date before merging" branch protection and press "Update" button.

**Comment by asvetlov** [comment]
Now the fix is merged, preparing a bugfix release

**Comment by jameshilliard** [comment]
> That's how github works when I enable "Require branches to be up to date before merging" branch protection and press "Update" button.

Weird, that's a strange way of implementing that feature.

**Comment by webknjaz** [comment]
@jameshilliard it's pretty standard. Besides, GitHub only blocks outdated PRs, it does not dictate a specific way of making it up-to-date. Another way is to ask the contributor, you, to do a rebase but this would mean more delays.

**Pull request merged**
