### PR TITLE
Fix deprecation warning from Jinja 3.0

### PR DESCRIPTION
**Pull request by ri-gilfanov**
Fix for:

`DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1`

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
The function is not available in jinja2<3, so it will need the requirements updated to jinja2>=3 as well:
https://github.com/ri-gilfanov/aiohttp-jinja2/blob/master/setup.py#L32

**Comment by Dreamsorcerer** [comment]
I've also just bumped the sphinx version in master, which should fix the CI issue.

**Comment by ri-gilfanov** [comment]
@Dreamsorcerer, I updated requirements in setup.py. Development requirements are successfully installed in a clear virtual environment with the latest versions of pip, setuptools and wheel. Tests are successfully also. At least for me.

**Comment by Dreamsorcerer** [comment]
Hmm, new Github seems to require me to approve every single test run...

**Pull request merged**
