### PR TITLE
Async rendering support

### LINKED ISSUE #333: Support async rendering
`template()` and `render_template()` should be async functions, or for backwards compatibility new async versions of the functions should be added.

They should call `jinja2.Template.render_async()`, which also requires `enable_async` in the environment setup.

See:
https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment
https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Template.render_async
https://jinja.palletsprojects.com/en/2.11.x/api/#async-support

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
-- This is branched from the typing PR, so merge that first to reduce the diff --

This adds `render_string_async()` and `render_template_async()` functions.
It also modifies the `@template` decorator to use the async rendering when `enable_async=True` has been passed to the setup.

Fixes #333

### CODE REVIEW

**Comment by asvetlov** [comment]
Please fix the merge conflict

**Comment by Dreamsorcerer** [comment]
OK, went a bit weird for a moment. All sorted now.

**Review by asvetlov — APPROVED** [review]

**Comment by asvetlov** [comment]
Awesome, I'll prepare a new release with this feature.

@Dreamsorcerer would you get write access to the repo (GitHub Maintainer role precisely).

I don't expect much work here but don't want to be a bus factor and shuffle off routine procedures on somebody else :)
Honestly, asyncio + aiohttp consumes almost all my spare time

**Comment by Dreamsorcerer** [comment]
Yep, go ahead. Happy to keep things going.

**Comment by asvetlov** [comment]
An invitation is sent.
I would suggest you maintain https://github.com/aio-libs/aiohttp-mako
The library is pretty similar to aiohttp-jinja2 but uses the mako template engine (which is simpler than jinja2 actually).
It needs some housekeeping work (drop py3.5, add tests for 3.8-3.9, maybe something also -- I don't remember).

**Pull request merged**
